apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller
  name: controller
spec:
  clusterIP: None
  ports:
  - name: rmi
    port: 55512
    protocol: TCP
    targetPort: 55512
  - name: vnc
    port: 5901
    protocol: TCP
    targetPort: 5901
  selector:
    app: controller
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: generator
  name: generator
spec:
  clusterIP: None
  ports:
  - name: rmi-registry
    port: 1099
    protocol: TCP
    targetPort: 1099
  - name: rmi-localport
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: generator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: generator
spec:
  selector:
    matchLabels:
      app: generator
  serviceName: "generator"
  replicas: 2
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: generator
        test: load
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: "In"
                  values: [ "generator", "controller" ]
            topologyKey: "kubernetes.io/hostname"
      hostname: generator
      containers:
      - name: generator
        image: rdpanek/jmeter:5.3.0
        command: ['/opt/apache-jmeter-5.3/bin/jmeter' ,'-Jserver.rmi.ssl.disable=true', '-Jserver.rmi.localport=1098', '-Dserver_port=1098', '--server']
        ports:
          # server port rmi registry
          - containerPort: 1098
          # server rmi local port
          - containerPort: 5001
        env:
        - name: Xmx
          value: "2g"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        imagePullPolicy: "IfNotPresent"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller
spec:
  selector:
    matchLabels:
      app: controller
  serviceName: "controller"
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
        test: load
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: "In"
                  values: [ "generator" ]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: controller
        image: rdpanek/jmeter:vnc-5.3.0
        ports:
        #client rmi local port
        - containerPort: 55512
        #dataserver master local port
        - containerPort: 9080
        env:
        - name: VNC_RESOLUTION
          value: "1920x1080"
        - name: VNC_PW
          value: "secret"
        - name: GIT_REVISION
          value: "4e44e02"
        - name: TEST_PLAN_NAME
          value: "examples/demoTestPlan.jmx"
        - name: GENERATORS
          value: "generator-0.generator:1098,generator-1.generator:1098"
        - name: GIT_REPOSITORY
          valueFrom:
            configMapKeyRef:
              name: jmeter-config
              key: repository
        - name: GIT_HOST
          valueFrom:
            configMapKeyRef:
              name: jmeter-config
              key: repository.host
        - name: GIT_PORT
          valueFrom:
            configMapKeyRef:
              name: jmeter-config
              key: repository.port
        - name: INTERNAL_PROXY
          valueFrom:
            configMapKeyRef:
              name: jmeter-config
              key: internal.proxy
        - name: INTERNAL_PROXY_PORT
          valueFrom:
            configMapKeyRef:
              name: jmeter-config
              key: internal.proxy.port
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        imagePullPolicy: "Always"
      initContainers:
      - name: wait-for-generators
        image: openshift/base-centos7
        command: ['/bin/bash', '-c', 'for i in {0..1}; do echo "generator-${i}.generator"; if ping -c 1 generator-${i}.generator &> /dev/null; then echo "exist"; else echo "no"; exit 1; fi; done;']
